# Generated by Django 3.2.5 on 2025-04-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250429_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('job_seeker', 'Job Seeker')], default='job_seeker', max_length=20),
        ),
    ]
