# Generated by Django 3.2.5 on 2025-04-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20250429_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='job',
            name='company_industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='company_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='company_website',
            field=models.URLField(blank=True),
        ),
    ]
