# Generated by Django 3.2.5 on 2025-05-06 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_add_categories'),
        ('job', '0016_auto_20250501_0223'),
    ]

    operations = [
    ]
