# Generated by Django 3.2.5 on 2025-05-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_merge_0014_add_categories_0016_auto_20250501_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary_max',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_min',
        ),
    ]
