# Generated by Django 3.2.5 on 2025-06-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_interview_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
    ]
